import type { Metadata } from 'next';
import { Inter, Andada_Pro } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const andadaPro = Andada_Pro({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${andadaPro.className} antialiased bg-gradient-to-br from-cyan-500 to-blue-600`}
      >
        {children}
      </body>
    </html>
  );
}
